server:
  port: 8082
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #    dialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
